### PR TITLE
Minor Bug

### PR DESCRIPTION
**Pull request by rnavaneeth992**
Issue: #180 

Changed the logo in footer and pixel quality also increased
Just reduced width in project card 

-
-
-

### CODE REVIEW

**Comment by rnavaneeth992** [comment]
image
image

**Comment by Vishesh-Vijay** [comment]
The CSS of the cards has not been changed yet properly. Kindly complete the task @rnavaneeth992 and then create the PR again. The task was to change all the cards whether they're of project,mentor and you were required to make the cards look more attractive and the size of the card images.

**Comment by Vishesh-Vijay** [comment]
and the opencode logo should be in the center of the opencode text in the footer @rnavaneeth992. You've till 12 midnight to complete the task. kindly create a pr before the deadline

**Comment by rnavaneeth992** [comment]
image

image

@Vishesh-Vijay is it ok now?

**Comment by Vishesh-Vijay** [comment]
The branch has conflicts @rnavaneeth992 kindly look into it

**Comment by rnavaneeth992** [comment]
Ok

**Pull request closed without merging**
