### PR TITLE
Leaderboard design

### PR DESCRIPTION
**Pull request by Rohit-110**
Issue: #124

### CODE REVIEW

**Comment by Vishesh-Vijay** [comment]
@Rohit-110  The design you've made would've been okay if there was some system of user login or something but since the website is open for all to see, the leaderboard should be designed according to those requirements. Kindly make those changes by 12.30 am

**Comment by Rohit-110** [comment]
@Vishesh-Vijay please review again

**Comment by Rohit-110** [comment]
@Vishesh-Vijay please review again

**Comment by Vishesh-Vijay** [comment]
@Rohit-110 just change the colours for the mobile view too and delete the previous design too and ill merge it then

**Comment by Rohit-110** [comment]
@Vishesh-Vijay made the changes, kindly review and merge

**Pull request merged**
