### PR TITLE
Added event section

### PR DESCRIPTION
**Pull request by Apoorv012**
Issue: #197 

#### Screenshot:
image

### CODE REVIEW

**Comment by Apoorv012** [comment]
btw, this felt more than a 10 points issue 😅

**Comment by Vishesh-Vijay** [comment]
@Apoorv012 have you added the events heading?

**Comment by Apoorv012** [comment]
Yes

**Comment by Vishesh-Vijay** [comment]
> btw, this felt more than a 10 points issue 😅

Card basic structure was already present in other sections and only little changes had to be done that's why it was for 5

**Comment by Apoorv012** [comment]
ok, np

**Pull request merged**
