### PR TITLE
Added Responsive Project section

### PR DESCRIPTION
**Pull request by Jarviss77**
Issue: #122

### CODE REVIEW

**Comment by Vishesh-Vijay** [comment]
@Jarviss77 you're required to put the screenshots of your changes with the PR. Kindly attach the ss of your changes and then if it's  okay i'll merge your PR

**Comment by Jarviss77** [comment]
Screenshot 2023-12-21 at 11 20 51 PM
Screenshot 2023-12-21 at 11 28 09 PM

**Comment by Vishesh-Vijay** [comment]
can you please show how does it look on a smallers screen @Jarviss77

**Comment by Jarviss77** [comment]
Screenshot 2023-12-21 at 11 31 02 PM

**Pull request merged**
