### PR TITLE
Created Design For the Homepage

### PR DESCRIPTION
**Pull request by Rohit-110**
Issue: #22

### CODE REVIEW

**Comment by GammaMicrowave** [comment]
I would reward you your points manually

**Comment by GammaMicrowave** [comment]
After the deadline.

**Comment by Rohit-110** [comment]
Ok Sir

**Comment by Rohit-110** [comment]
@GammaMicrowave Sir, kindly reward for this task

**Comment by GammaMicrowave** [comment]
Ya I would do it tommorow as I have given my laptop for repair so I cannot access the leaderboard right now.

**Comment by Rohit-110** [comment]
@GammaMicrowave  Sir kindly reward for the task

**Pull request merged**
