### PR TITLE
Update participants.json

### PR DESCRIPTION
**Pull request by deepanshunegi06**
Issue: #ISSUENUMBER

I add my details in participant.json

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by deepanshunegi06** [comment]
This is my first contribution and really don't know how to use github but i  am trying

**Comment by GammaMicrowave** [comment]
ah try opening a new PR as the bot didnt recongnize this PR since you closed it @deepanshunegi06.

**Comment by GammaMicrowave** [comment]
I am closing this one just make a new PR the way you made this one and the bot would recongnize it.

**Comment by deepanshunegi06** [comment]
I can't understand what you want to say because I am very new to GitHub

**Pull request closed without merging**
